#!/usr/bin/env python3

import os
import sys
from helpers import eprint

# grip-init is my implementation of the grip-init command.
# Edwin Tang (z5482091)
# Implementation ===============================================================

grip = '.grip'
commitDir = '.grip/commits'
currState = '.grip/curr'

if __name__ == "__main__":
    # Verifying command line arguments
    if len(sys.argv) != 1:
        print("usage: grip-init", file=sys.stderr)
        sys.exit(1)
    # Checking if .grip already exists
    if os.path.exists(grip):
        if not os.path.exists(commitDir):
            os.mkdir(commitDir)
        if not os.path.exists(currState):
            os.mkdir(currState)
        eprint(sys.argv[0], ".grip already exists")
        sys.exit(1)
    # Making the .grip directory
    try:
        os.mkdir(grip)
        os.mkdir(commitDir)
        os.mkdir(currState)
        print("Initialized empty grip repository in .grip")
    except OSError as error:  
        eprint(sys.argv[0], "could not create grip repository")
        sys.exit(1)